"""TOPS deramping / demodulation for Sentinel-1 IW SLC bursts.

Implements ESA's "Definition of the TOPS SLC deramping function for products
generated by the S-1 IPF" (COPE-GSEG-EOPG-TN-14-0025, Issue 1, Rev 3):

    deramp:               s' = s * exp(-j*pi*kt(tau)*(eta - eta_ref(tau))^2)
    deramp + demodulate:  s' = s * exp(-j*pi*kt*(eta - eta_ref)^2 - j*2*pi*f_dc*(eta - eta_ref))

    ks   = (2 vs / lambda) * k_psi                 antenna-steering Doppler rate [Hz/s]
    kt   = ka * ks / (ka - ks)                     Doppler centroid rate in the SLC [Hz/s]
    eta_c(tau)   = -f_dc(tau) / ka(tau)
    eta_ref(tau) = eta_c(tau) - eta_c(N_samples / 2)
    eta          = (n - N_lines/2) * dt,  n = 0 .. N_lines-1   (time from burst centre)

ka (azimuth FM rate) and f_dc (Doppler centroid) are range polynomials taken
from the record nearest to the mid-burst time. k_psi is annotated in deg/s.

Demodulation moves the azimuth spectrum to baseband (centre ~ 0 Hz). The same
function must be applied to VV and VH. C12 = S_vv * conj(S_vh) is unchanged by
any phase applied identically to both channels; deramping matters because it
puts the spectrum where the sub-look band split expects it.

Usage:
    python -m sar_denoise.deramp /path/to/product.SAFE iw2 vv [--burst K] [--plot out.png]
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass

import numpy as np
from numpy.polynomial import polynomial as P

C_LIGHT = 299792458.0


@dataclass
class DerampParams:
    tau: np.ndarray        # (n_samples,) two-way slant range time [s]
    k_a: np.ndarray        # Doppler FM rate [Hz/s] (negative)
    f_dc: np.ndarray       # Doppler centroid [Hz]
    k_s: float             # antenna-steering Doppler rate [Hz/s]
    k_t: np.ndarray        # Doppler centroid rate in the SLC [Hz/s]
    eta_ref: np.ndarray    # reference zero-Doppler time [s]
    v_s: float             # spacecraft speed at mid-burst [m/s]
    t_mid: np.datetime64   # mid-burst azimuth time


def antenna_doppler_rate(v_s: float, radar_frequency: float, steering_rate_deg_s: float) -> float:
    """ks = (2 vs / lambda) * k_psi, with k_psi converted from deg/s to rad/s."""
    wavelength = C_LIGHT / radar_frequency
    return 2.0 * v_s / wavelength * np.deg2rad(steering_rate_deg_s)


def burst_mid_time(info, burst) -> np.datetime64:
    """eta_mid = eta_start + dt * N_lines / 2."""
    half_ns = int(round(info.azimuth_time_interval * burst.n_lines / 2.0 * 1e9))
    return burst.azimuth_time + np.timedelta64(half_ns, "ns")


def _nearest(polys, t_mid):
    if not polys:
        raise ValueError("no polynomial records available")
    gaps = [abs((p.azimuth_time - t_mid) / np.timedelta64(1, "s")) for p in polys]
    return polys[int(np.argmin(gaps))]


def spacecraft_speed(info, t_mid) -> float:
    """Speed |v| interpolated to t_mid from the orbit state vectors."""
    if len(info.orbit_times) < 2:
        raise ValueError("need at least two orbit state vectors")
    t = (info.orbit_times - t_mid) / np.timedelta64(1, "s")
    return float(np.interp(0.0, t, info.orbit_speeds))


def deramp_params(info, burst_index: int) -> DerampParams:
    burst = info.bursts[burst_index]
    t_mid = burst_mid_time(info, burst)

    tau = info.slant_range_time + np.arange(burst.n_samples) / info.range_sampling_rate
    fm = _nearest(info.fm_rates, t_mid)
    dc = _nearest(info.dc_estimates, t_mid)
    k_a = P.polyval(tau - fm.t0, fm.coeffs)
    f_dc = P.polyval(tau - dc.t0, dc.coeffs)

    v_s = spacecraft_speed(info, t_mid)
    k_s = antenna_doppler_rate(v_s, info.radar_frequency, info.azimuth_steering_rate)
    k_t = k_a * k_s / (k_a - k_s)

    eta_c = -f_dc / k_a
    eta_ref = eta_c - eta_c[info.n_samples // 2]
    return DerampParams(tau, k_a, f_dc, k_s, k_t, eta_ref, v_s, t_mid)


def deramp_phase(params: DerampParams, eta: np.ndarray, demodulate: bool = True) -> np.ndarray:
    """Phase to ADD to the data, shape (len(eta), n_samples). (Data is multiplied by exp(j*phase).)"""
    x = eta[:, None] - params.eta_ref[None, :]
    phase = -np.pi * params.k_t[None, :] * x * x
    if demodulate:
        phase = phase - 2.0 * np.pi * params.f_dc[None, :] * x
    return phase


def deramp_burst(data: np.ndarray, info, burst_index: int, demodulate: bool = True,
                 chunk_lines: int = 128) -> np.ndarray:
    """Deramp (and by default demodulate) one burst; returns complex64, same shape.

    Works in chunks of lines so the float64 phase array never gets large.
    """
    burst = info.bursts[burst_index]
    if data.shape != (burst.n_lines, burst.n_samples):
        raise ValueError(f"data shape {data.shape} != burst shape {(burst.n_lines, burst.n_samples)}")
    params = deramp_params(info, burst_index)
    dt = info.azimuth_time_interval
    eta = (np.arange(burst.n_lines) - burst.n_lines / 2.0) * dt

    out = np.empty(data.shape, dtype=np.complex64)
    for i0 in range(0, burst.n_lines, chunk_lines):
        i1 = min(i0 + chunk_lines, burst.n_lines)
        phase = deramp_phase(params, eta[i0:i1], demodulate)
        out[i0:i1] = data[i0:i1] * np.exp(1j * phase).astype(np.complex64)
    return out


# ---------------------------------------------------------------- diagnostics
def mean_azimuth_spectrum(block: np.ndarray, dt: float, column_step: int = 8):
    """Power spectrum along azimuth, averaged over range columns.

    Returns (freq [Hz], power), both fftshifted. A Hann taper limits leakage.
    """
    x = block[:, ::column_step]
    n = x.shape[0]
    win = np.hanning(n).astype(np.float32)[:, None]
    spec = np.fft.fft(x * win, axis=0)
    power = np.mean(np.abs(spec) ** 2, axis=1)
    freq = np.fft.fftfreq(n, d=dt)
    return np.fft.fftshift(freq), np.fft.fftshift(power)


def spectrum_stats(freq: np.ndarray, power: np.ndarray) -> dict:
    """Centroid and 5-95 % energy width of a spectrum."""
    p = power / power.sum()
    centroid = float(np.sum(freq * p))
    cdf = np.cumsum(p)
    lo = float(freq[np.searchsorted(cdf, 0.05)])
    hi = float(freq[min(np.searchsorted(cdf, 0.95), len(freq) - 1)])
    return {"centroid_hz": centroid, "p05_hz": lo, "p95_hz": hi, "width_hz": hi - lo}


def main() -> None:
    from sar_denoise.safe_io import find_swath_files, parse_annotation, read_burst

    ap = argparse.ArgumentParser(description="Deramp one burst and report azimuth-spectrum statistics")
    ap.add_argument("safe_dir")
    ap.add_argument("swath")
    ap.add_argument("pol")
    ap.add_argument("--burst", type=int, default=None)
    ap.add_argument("--plot", default=None, help="save a before/after spectrum figure to this path")
    args = ap.parse_args()

    tiff, xml = find_swath_files(args.safe_dir, args.swath, args.pol)
    info = parse_annotation(xml)
    k = args.burst if args.burst is not None else len(info.bursts) // 2
    b = info.bursts[k]
    l0, l1 = b.valid_line_range
    s0, s1 = b.valid_sample_range

    p = deramp_params(info, k)
    print(f"burst {k}: mid time {p.t_mid}, spacecraft speed {p.v_s:.2f} m/s")
    print(f"ks (antenna steering)   : {p.k_s:.1f} Hz/s")
    print(f"ka (FM rate)            : {p.k_a.min():.1f} .. {p.k_a.max():.1f} Hz/s")
    print(f"kt (centroid rate)      : {p.k_t.min():.1f} .. {p.k_t.max():.1f} Hz/s")
    print(f"f_dc (Doppler centroid) : {p.f_dc.min():.1f} .. {p.f_dc.max():.1f} Hz")
    print(f"eta_ref                 : {p.eta_ref.min() * 1e3:.3f} .. {p.eta_ref.max() * 1e3:.3f} ms")

    data = read_burst(tiff, info, k)
    dt = info.azimuth_time_interval
    variants = {
        "raw": data,
        "deramped": deramp_burst(data, info, k, demodulate=False),
        "deramped + demodulated": deramp_burst(data, info, k, demodulate=True),
    }
    spectra = {}
    print(f"\nazimuth sampling {1.0 / dt:.1f} Hz, annotated processing bandwidth "
          f"{info.processing_bandwidth} Hz")
    for name, arr in variants.items():
        f, pw = mean_azimuth_spectrum(arr[l0:l1, s0:s1], dt)
        st = spectrum_stats(f, pw)
        spectra[name] = (f, pw)
        print(f"{name:24s}: centroid {st['centroid_hz']:7.1f} Hz, "
              f"5-95% band {st['p05_hz']:7.1f} .. {st['p95_hz']:7.1f} Hz (width {st['width_hz']:.1f} Hz)")

    if args.plot:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(8, 4))
        for name, (f, pw) in spectra.items():
            ax.plot(f, 10 * np.log10(pw / pw.max()), label=name)
        ax.set_xlabel("azimuth frequency [Hz]")
        ax.set_ylabel("relative power [dB]")
        ax.set_ylim(-40, 3)
        ax.grid(alpha=0.3)
        ax.legend()
        fig.tight_layout()
        fig.savefig(args.plot, dpi=150)
        print(f"saved {args.plot}")


if __name__ == "__main__":
    main()